#!/usr/bin/env bash
set -e

# ==============================================================================
#  Tau Installer
#  Automated installer for Tau container engine and package manager.
# ==============================================================================

BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
RESET="\033[0m"

log_info()    { echo -e "${BOLD}${GREEN}==>${RESET} ${BOLD}$1${RESET}"; }
log_warn()    { echo -e "${YELLOW}Warning:${RESET} $1"; }
log_error()   { echo -e "${RED}Error:${RESET} $1" >&2; }

IS_ROOT=0
if [ "$(id -u)" -eq 0 ]; then
    IS_ROOT=1
fi

# ─── 1. Ensure / Install Dependencies ─────────────────────────────────────────

REQUIRED_BINS=("cmake" "git" "ccache")
C_COMPILERS=("clang" "clang++" "gcc" "g++")
NINJA_BINS=("ninja" "ninja-build")

has_compiler() {
    command -v clang >/dev/null 2>&1 || command -v gcc >/dev/null 2>&1
}

has_ninja() {
    command -v ninja >/dev/null 2>&1 || command -v ninja-build >/dev/null 2>&1
}

if [ "$IS_ROOT" -eq 1 ]; then
    log_info "Detected root privileges. Ensuring toolchain dependencies..."

    if command -v apt-get >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y clang cmake ninja-build ccache git build-essential
    elif command -v dnf >/dev/null 2>&1; then
        dnf install -y clang cmake ninja-build ccache git gcc-c++
    elif command -v pacman >/dev/null 2>&1; then
        pacman -Sy --noconfirm clang cmake ninja ccache git base-devel
    elif command -v zypper >/dev/null 2>&1; then
        zypper --non-interactive install clang cmake ninja ccache git gcc-c++
    elif command -v apk >/dev/null 2>&1; then
        apk add clang cmake ninja ccache git build-base linux-headers
    else
        log_warn "Unknown package manager. Checking existing system tools..."
    fi
fi

# Verify dependencies exist
MISSING=()
for b in "${REQUIRED_BINS[@]}"; do
    if ! command -v "$b" >/dev/null 2>&1; then
        MISSING+=("$b")
    fi
done

if ! has_compiler; then
    MISSING+=("clang/gcc")
fi

if ! has_ninja; then
    MISSING+=("ninja")
fi

if [ ${#MISSING[@]} -gt 0 ]; then
    log_error "Missing required dependencies: ${MISSING[*]}"
    log_error "Please install them via your package manager or rerun this script with root/sudo."
    exit 1
fi

log_info "All toolchain dependencies satisfied."

# ─── 2. Setup TAU_PATH ────────────────────────────────────────────────────────

if [ "$IS_ROOT" -eq 1 ]; then
    TAU_PATH="/.var/tau"
else
    TAU_PATH="${HOME}/.var/tau"
fi

log_info "Using TAU_PATH: ${TAU_PATH}"
mkdir -p "${TAU_PATH}"
mkdir -p "${TAU_PATH}/manifests"
mkdir -p "${TAU_PATH}/store"
mkdir -p "${TAU_PATH}/githubCache"

if [ "$IS_ROOT" -eq 1 ]; then
    chmod 0777 "${TAU_PATH}/manifests" || true
fi

# ─── 3. Clone or Update Tau Source ────────────────────────────────────────────

SOURCE_DIR="${TAU_PATH}/source"

if [ -d "${SOURCE_DIR}/.git" ]; then
    log_info "Updating Tau repository in ${SOURCE_DIR}..."
    git -C "${SOURCE_DIR}" fetch --all --prune
    git -C "${SOURCE_DIR}" reset --hard origin/main || git -C "${SOURCE_DIR}" pull --ff-only || true
else
    log_info "Cloning Tau into ${SOURCE_DIR}..."
    rm -rf "${SOURCE_DIR}"
    git clone https://github.com/ksee6/tau.git "${SOURCE_DIR}"
fi

# ─── 4. Build Tau ─────────────────────────────────────────────────────────────

BUILD_DIR="${SOURCE_DIR}/build"
log_info "Configuring build in ${BUILD_DIR}..."

CMAKE_GENERATOR="Unix Makefiles"
if has_ninja; then
    CMAKE_GENERATOR="Ninja"
fi

cmake -B "${BUILD_DIR}" -S "${SOURCE_DIR}" \
      -DCMAKE_BUILD_TYPE=Release \
      -G "${CMAKE_GENERATOR}"

log_info "Building Tau..."
cmake --build "${BUILD_DIR}" --parallel

# ─── 5. Install Symlinks & Set Sudoers Policy ─────────────────────────────────

chmod 0755 "${BUILD_DIR}/tau"

if [ "$IS_ROOT" -eq 1 ]; then
    log_info "Configuring passwordless sudoers rule for tau do-store..."
    SUDOERS_FILE="/etc/sudoers.d/tau"
    mkdir -p "/etc/sudoers.d"
    cat << EOF > "${SUDOERS_FILE}"
# Automatically generated by Tau installer
# Allows passwordless execution of tau do-store only (no arguments) for store management
ALL ALL=(root) NOPASSWD: ${BUILD_DIR}/tau do-store, /usr/local/bin/tau do-store, /usr/bin/tau do-store
EOF
    chmod 0440 "${SUDOERS_FILE}"
    if command -v visudo >/dev/null 2>&1; then
        if ! visudo -cf "${SUDOERS_FILE}" >/dev/null 2>&1; then
            log_warn "visudo syntax check failed on ${SUDOERS_FILE}; removing."
            rm -f "${SUDOERS_FILE}"
        fi
    fi

    # Install into system-wide bin directories
    for SYSTEM_BIN in "/usr/local/bin" "/usr/bin"; do
        if [ -d "${SYSTEM_BIN}" ] && [ -w "${SYSTEM_BIN}" ]; then
            log_info "Installing binaries into system-wide directory: ${SYSTEM_BIN}..."
            ln -sf "${BUILD_DIR}/tau"          "${SYSTEM_BIN}/tau"
            ln -sf "${BUILD_DIR}/tau"          "${SYSTEM_BIN}/tgh"
            break
        fi
    done
else
    # Non-root installer: check if sudo is available to configure sudoers
    if command -v sudo >/dev/null 2>&1 && sudo -n true 2>/dev/null; then
        log_info "Configuring passwordless sudoers rule via sudo..."
        SUDOERS_TMP=$(mktemp)
        cat << EOF > "${SUDOERS_TMP}"
# Automatically generated by Tau installer
# Allows passwordless execution of tau do-store only (no arguments) for store management
ALL ALL=(root) NOPASSWD: ${BUILD_DIR}/tau do-store, ${HOME}/.local/bin/tau do-store
EOF
        sudo mkdir -p "/etc/sudoers.d"
        sudo cp "${SUDOERS_TMP}" "/etc/sudoers.d/tau"
        sudo chmod 0440 "/etc/sudoers.d/tau"
        rm -f "${SUDOERS_TMP}"
    fi

    # Install into user-wide bin directory
    USER_BIN_DIR="${HOME}/.local/bin"
    mkdir -p "${USER_BIN_DIR}"

    log_info "Installing binaries into user-wide directory: ${USER_BIN_DIR}..."
    ln -sf "${BUILD_DIR}/tau"          "${USER_BIN_DIR}/tau"
    ln -sf "${BUILD_DIR}/tau"          "${USER_BIN_DIR}/tgh"

    if [ -d "${HOME}/bin" ]; then
        ln -sf "${BUILD_DIR}/tau"          "${HOME}/bin/tau"
        ln -sf "${BUILD_DIR}/tau"          "${HOME}/bin/tgh"
    fi

    if [[ ":$PATH:" != *":${USER_BIN_DIR}:"* ]]; then
        log_warn "${USER_BIN_DIR} is not in your \$PATH."
        log_warn "Add it by placing this in your shell profile (~/.bashrc or ~/.zshrc):"
        echo 'export PATH="$HOME/.local/bin:$PATH"'
    fi
fi

# ─── 6. Verification ──────────────────────────────────────────────────────────

log_info "Verifying installation..."
"${BUILD_DIR}/tau" --version

echo ""
echo -e "${BOLD}${GREEN}====================================================${RESET}"
echo -e "${BOLD}${GREEN} Tau successfully installed and configured!         ${RESET}"
echo -e "${BOLD}${GREEN}====================================================${RESET}"
echo ""
